### ISSUE TITLE
Update Request Parameters

### ISSUE THREAD

**Issue by IbottaBaier** [aws/aws-sdk-ruby-record#62] opened 2017-04-11 21:50 UTC
`Record.update!` only accepts record attributes as parameters, disallowing the configuration of 'return_value' or 'return_consumed_capacity'.

To reiterate my solution describe in #59:

To handle this I created a `SimpleDelegator` which delegates an `Aws::DynamoDB::Client` and provides additional functionality:
```
  class InterceptClient < SimpleDelegator

    attr_accessor :update_item_params

    # inject additional parameters for update requests
    def update_item(request)
      super(request.merge(update_item_params))
    end
  end
```

I then created a `new_client` function for generating clients (mainly exposed to be overridden in test, if necessary):
```
      # Spawns a new client with necessary request parameter overrides.
      def self.new_client
        client = InterceptClient.new(Aws::DynamoDB::Client.new(stub_responses: Rails.env.test?))
        client.update_item_params = { return_values: 'ALL_NEW' }
        client
      end
```

This is severely limiting due to the fact that the class and all instances share the same client - this means ALL updates must return 'ALL_NEW' attributes; there is no way to (safely) change that value in a multi-threaded environment (using Shoryuken for processing SQS messages and reading/writing Dynamo).

**Comment by awood45** [comment] 2017-04-14 16:13
I hear what you're saying. I think since a V2 bump is planned anyways to support the modularized SDK, I may look to include some API adjustments.

**Comment by mullermp** [comment] 2022-04-12 22:21
Duplicate of #59

**Closed by mullermp** 2022-04-12 22:21 UTC
