### ISSUE TITLE
Nested attributes / associations?

### ISSUE THREAD

**Issue by 1kevinxu1** [aws/aws-sdk-ruby-record#44] opened 2016-11-04 05:17 UTC
Hi, I'm using DynamoDB to store some user metadata. The idea being that I can query for a single user ID to find sets of data about that user. Think of a soundcloud-like app where users have different playlists of songs: "Electronic", "Shower Music", "Graduation Playlist". 

The document would look something like this:

```
{
  "uuid": 87,
  "playlists": [
      {
          "name": "Electronic",
          "songs": [12, 17, 33, 24, 49]
      },
      (
           "name": "Shower Music",
           "songs": [4, 15, 7]
      } ,
      {    "name": "Graduation Playlist"
           "songs":  [42]
      }
   ]
}
```

However, after digging through your documentation/source code (maybe I didn't dig deep enough?), I can't seem to find anywhere that gives the ability to define nested hashes by default on the models. Is this intended—models should only have single-level attributes? The solution that comes to mind for me is associations, but I don't think aws-record supports associations (correct me if I'm wrong).

What's the best way to move forward on this?

**Comment by 1kevinxu1** [comment] 2016-11-04 05:35
Wait... it just hit me how dumb of a question this is. It's late at night so that's my excuse 😞

**Comment by awood45** [comment] 2016-11-04 05:37
It's not really a dumb question, let's take a deeper look at it.

You're right that `aws-record` does not provide nested types, which is by design - it is not a persistence concern. However, you can accomplish what you're trying to do if you combine with `ActiveModel::Validations`. Consider first what your model would look like using just `aws-record`:

```ruby
require 'aws-record'

class Playlist
  include Aws::Record
  string_attr :uuid, hash_key: true
  list_attr   :playlists, default_value: []
end
```

You'll note that I switched the type of `:uuid`, since a UUID a la `SecureRandom.uuid` won't be an integer. You could swap that if you like. In any case, here is an example of a validation you could write to accomplish what you want to do:

```ruby
require 'aws-record'
require 'active_model'

class Playlist
  include Aws::Record
  include ActiveModel::Validations

  string_attr :uuid, hash_key: true
  list_attr   :playlists, default_value: []

  validates_each :playlists do |record, attr, value|
    shape_valid = value.all? do |playlist|
      if playlist.is_a?(Hash)
        playlist["name"] && playlist["name"].is_a?(String) &&
          playlist["songs"] && playlist["songs"].is_a?(Array) &&
          playlist["songs"].all? { |song| song.is_a?(Integer) }
      else
        false
      end
    end
    record.errors.add attr, "is not an array of valid playlists" unless shape_valid
  end
end
```

It's a bit hacked together, but I think you could take it from here to get the validations you want.

**Comment by awood45** [comment] 2016-11-04 05:40
FWIW, and I'll blame the late hour also, that validation has a good number of edge cases to it, but it's more meant to illustrate that you can bring your own nested shape validation if you want. However, DynamoDB is not going to enforce it on the server side, all it sees is that it has a key attribute called `:uuid`. The rest is a construct of how we use it.

Closing this as I think the question is answered. If you have any follow-up questions, don't hesitate to add them on.

**Closed by awood45** 2016-11-04 05:40 UTC
Labels: question
